### ISSUE TITLE
Need to update module

### ISSUE THREAD

**Issue by Alexxxunchained** [Qbox-project/qbx_bankrobbery#25]
### Summary

When started resource there an warnning to update to newest module

### Reproduction

![微信图片_20240716062317](https://github.com/user-attachments/assets/cf307749-d325-4757-93ae-a3f58e0471f6)
And I dont know why, the powerstation part is not working at all.

### Expected behavior

To be working

### Actual behavior

Not working at all

### Current Version

V1.0.0

### Custom Resources

No

**Comment by solareon** [comment]
Please download the latest GitHub commit. This issue has been fixed for quite awhile now.
